{-# OPTIONS_GHC -Wno-missing-export-lists #-}
module EulerQuestions where

-- ANCHOR Q1
-- If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
-- Find the sum of all the multiples of 3 or 5 below 1000.
isMultipleOf :: Int -> Int -> Bool
x `isMultipleOf` y = x `rem` y == 0

-- Input 1000 -> 
sumOfMultiplesOf3Or5 :: Int -> Int
sumOfMultiplesOf3Or5 maxExclusive
  = sum (filter  (\x -> x `isMultipleOf` 3 || x `isMultipleOf` 5) [0 .. (maxExclusive - 1)])

-- ANCHOR Q2
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
-- By starting with 1 and 2, the first 10 terms will be:
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
-- find the sum of the even-valued terms.